INSERT INTO ingredients (ingredientName, ingredientCategoryId, costEstimate, origin, isVegan, isVegetarian, isAllergen, storageAdvice, description, shelfLifeFridge, shelfLifeFreezer, shelfLifeOutside, shelfLifeOpened) VALUES
('Beurre', NULL, 1.5, 'France', false, false, true, 'Conserver au réfrigérateur', 'Beurre doux', 30, 180, 7, 7),
('Tomate', NULL, 0.5, 'France', true, true, false, 'Conserver au frais', 'Tomate ronde', 7, NULL, 3, 2),
('Oignon', NULL, 0.2, 'France', true, true, false, 'Conserver au sec et à l''ombre', 'Oignon jaune', 30, NULL, 60, 14),
('Ail', NULL, 0.1, 'Espagne', true, true, false, 'Conserver au sec', 'Gousse d''ail', 30, NULL, 120, 30),
('Huile d''olive', NULL, 6.0, 'Italie', true, true, false, 'Conserver à température ambiante', 'Huile extra vierge', NULL, 365, NULL, 365),
('Sel', NULL, 0.05, 'France', true, true, false, 'Conserver au sec', 'Sel fin', NULL, NULL, NULL, NULL),
('Poivre noir', NULL, 0.1, 'Inde', true, true, false, 'Conserver au sec', 'Grains de poivre moulus', 365, NULL, 365, 365),
('Sucre', NULL, 0.05, 'France', true, true, false, 'Conserver au sec', 'Sucre blanc', 365, NULL, 365, 365),
('Farine de blé', NULL, 0.4, 'France', true, true, false, 'Conserver au sec', 'Farine T45', 180, NULL, 365, 30),
('Lait', NULL, 1.0, 'France', false, false, false, 'Conserver au réfrigérateur', 'Lait entier', 7, NULL, 2, 3),
('Oeuf', NULL, 0.25, 'France', false, false, false, 'Conserver au réfrigérateur', 'Oeuf de poule', 28, NULL, 7, 7),
('Fromage râpé', NULL, 2.5, 'France', false, false, true, 'Conserver au réfrigérateur', 'Emmental râpé', 14, 90, NULL, 7),
('Mozzarella', NULL, 1.8, 'Italie', false, false, true, 'Conserver au réfrigérateur', 'Mozzarella fraîche', 7, NULL, NULL, 3),
('Jambon', NULL, 2.0, 'France', false, false, true, 'Conserver au réfrigérateur', 'Jambon cuit', 7, 90, NULL, 3),
('Poulet', NULL, 3.0, 'France', false, false, false, 'Conserver au réfrigérateur ou congeler', 'Filet de poulet', 2, 180, 1, 2),
('Boeuf haché', NULL, 4.0, 'France', false, false, false, 'Conserver au réfrigérateur ou congeler', 'Steak haché', 2, 180, 1, 1),
('Poisson blanc', NULL, 4.5, 'Norvège', false, false, false, 'Conserver au réfrigérateur ou congeler', 'Cabillaud', 2, 180, 1, 1),
('Crevette', NULL, 6.0, 'Asie', false, false, true, 'Conserver au réfrigérateur ou congeler', 'Crevettes décortiquées', 2, 180, 1, 1),
('Riz', NULL, 0.8, 'France', true, true, false, 'Conserver au sec', 'Riz long grain', 365, NULL, 365, 365),
('Pates', NULL, 0.7, 'Italie', true, true, false, 'Conserver au sec', 'Spaghetti', 365, NULL, 365, 365),
('Pommes de terre', NULL, 0.6, 'France', true, true, false, 'Conserver au sec', 'Pommes de terre a chair ferme', 30, NULL, 90, 7),
('Carotte', NULL, 0.3, 'France', true, true, false, 'Conserver au réfrigérateur', 'Carotte fraîche', 21, NULL, 14, 7),
('Courgette', NULL, 0.5, 'France', true, true, false, 'Conserver au réfrigérateur', 'Courgette', 7, NULL, 3, 3),
('Aubergine', NULL, 0.7, 'France', true, true, false, 'Conserver à température ambiante', 'Aubergine', 7, NULL, 3, 3),
('Poivron', NULL, 0.9, 'Espagne', true, true, false, 'Conserver au réfrigérateur', 'Poivron rouge', 10, NULL, 3, 3),
('Champignon de Paris', NULL, 1.2, 'France', true, true, false, 'Conserver au réfrigérateur', 'Champignon blanc', 7, NULL, 3, 2),
('Basilic', NULL, 0.8, 'France', true, true, false, 'Conserver au frais dans un verre d''eau', 'Feuilles de basilic', 7, NULL, 2, 2),
('Persil', NULL, 0.5, 'France', true, true, false, 'Conserver au réfrigérateur', 'Persil plat', 7, NULL, 3, 3),
('Thym', NULL, 0.2, 'France', true, true, false, 'Conserver au sec', 'Branche de thym', 365, NULL, 365, 365),
('Romarin', NULL, 0.3, 'France', true, true, false, 'Conserver au sec', 'Branche de romarin', 365, NULL, 365, 365),
('Citron', NULL, 0.6, 'Espagne', true, true, false, 'Conserver au réfrigérateur', 'Citron jaune', 30, NULL, 7, 7),
('Orange', NULL, 0.6, 'Espagne', true, true, false, 'Conserver à température ambiante', 'Orange', 21, NULL, 14, 7),
('Concombre', NULL, 0.7, 'France', true, true, false, 'Conserver au réfrigérateur', 'Concombre', 7, NULL, 3, 3),
('Laitue', NULL, 1.0, 'France', true, true, false, 'Conserver au réfrigérateur', 'Laitue romaine', 7, NULL, 3, 3),
('Epinard', NULL, 1.2, 'France', true, true, false, 'Conserver au réfrigérateur', 'Epinards frais', 5, NULL, 2, 2),
('Noix', NULL, 3.5, 'France', true, true, true, 'Conserver au sec', 'Noix decortiquees', 180, 365, 365, 60),
('Amande', NULL, 4.0, 'Etats-Unis', true, true, true, 'Conserver au sec', 'Amandes', 180, 365, 365, 60),
('Beurre de cacahuete', NULL, 3.0, 'Etats-Unis', true, true, true, 'Conserver à température ambiante', 'Beurre de cacahuete', 365, NULL, 365, 90),
('Chocolat', NULL, 2.0, 'Belgique', true, true, false, 'Conserver au sec', 'Chocolat noir', 365, NULL, 365, 180),
('Miel', NULL, 5.0, 'France', true, true, false, 'Conserver à température ambiante', 'Miel de fleurs', NULL, NULL, NULL, 365),
('Levure boulangere', NULL, 0.6, 'France', true, true, false, 'Conserver au sec', 'Levure seche', 365, NULL, 365, 180),
('Vinaigre balsamique', NULL, 4.0, 'Italie', true, true, false, 'Conserver à température ambiante', 'Vinaigre', NULL, NULL, NULL, 365),
('Sauce soja', NULL, 2.0, 'Japon', true, true, false, 'Conserver au sec', 'Sauce soja salee', 365, NULL, 365, 365),
('Curry en poudre', NULL, 1.5, 'Inde', true, true, false, 'Conserver au sec', 'Mélange d''épices curry', 365, NULL, 365, 365),
('Paprika', NULL, 0.9, 'Hongrie', true, true, false, 'Conserver au sec', 'Paprika doux', 365, NULL, 365, 365),
('Cannelle', NULL, 1.2, 'Sri Lanka', true, true, false, 'Conserver au sec', 'Bâtons de cannelle', 365, NULL, 365, 365),
('Gingembre', NULL, 1.3, 'Asie', true, true, false, 'Conserver au réfrigérateur', 'Racine de gingembre', 14, 180, 7, 7),
('Lentilles', NULL, 1.0, 'France', true, true, false, 'Conserver au sec', 'Lentilles vertes', 365, NULL, 365, 365),
('Pois chiches', NULL, 0.9, 'France', true, true, false, 'Conserver au sec', 'Pois chiches secs', 365, NULL, 365, 365);
